name: Test and coverage

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test-and-coverage:
    if: "!contains(github.event.head_commit.message, 'ci: version bump') && github.actor != 'dependabot[bot]'"
    name: test-and-coverage
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.14.1'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Unit test
        run: yarn test

      - uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn coverage
