name: Publish

on:
  push:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_VERSION: '16.15.0'

jobs:
  bump:
    if: "!contains(github.event.head_commit.message, 'ci: version bump')"
    runs-on: ubuntu-20.04
    outputs:
      sha: ${{ steps.step3.outputs.sha }}
      newTag: ${{ steps.step2.outputs.newTag }}
    steps:
      - id: step1
        name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}

      - id: step2
        name: Automated Version Bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        with:
          tag-prefix: ''
          target-branch: 'master'

      - id: step3
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

  publish:
    if: "!contains(github.event.head_commit.message, 'ci: version bump')"
    name: Publish to NPM
    runs-on: ubuntu-20.04
    needs: [bump]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.bump.outputs.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - name: Publish
        run: npm publish --access public

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.bump.outputs.newTag }}
          token: ${{ secrets.GH_ADMIN_TOKEN }}
  docs:
    if: "!contains(github.event.head_commit.message, 'ci: version bump')"
    name: Publish docs to GitHub Wiki
    runs-on: ubuntu-20.04
    needs: [bump]
    steps:
      - name: Checkout library code
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.bump.outputs.sha }}
          path: library

      - name: Checkout wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          path: docs

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: library/yarn.lock

      - working-directory: ./library
        run: yarn install

      - working-directory: ./library
        run: yarn build

      - working-directory: ./library
        run: yarn doc

      - name: Copy docs to wiki repo
        run: |
          rsync -r ./library/docs/ ./docs

      - name: Push the updated docs
        working-directory: ./docs
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add .
          git commit -m 'Update docs for library version ${{ needs.bump.outputs.newTag }}'
          git push
